#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.
#
# chkconfig:   - 85 15
# description:  Redis is a persistent key-value database
# processname: redis

REDISPORT=6379
EXEC=/usr/local/bin/redis-server
CLIEXEC=/usr/local/bin/redis-cli
SERVICENAME=redis

# PIDFILE=/var/run/redis_${REDISPORT}.pid
# CONF="/etc/redis/${REDISPORT}.conf"
PIDFILE=/var/run/$SERVICENAME.pid
CONF="/etc/redis/$SERVICENAME.conf"

# Get some handy functions (namely "status()")
source /etc/rc.d/init.d/functions

start(){
    if [ -f $PIDFILE ]
    then
            echo "Redis is running"
            return 0
    else
            echo "Starting Redis server..."
            $EXEC $CONF
    fi
}

stop(){
    if [ ! -f $PIDFILE ]
    then
            echo "Redis is not running"
            return 0
    else
            PID=$(cat $PIDFILE)
            echo "Stopping ..."
            $CLIEXEC -p $REDISPORT shutdown
            while [ -x /proc/${PID} ]
            do
                echo "Waiting for Redis to shutdown ..."
                sleep 1
            done
            echo "Redis stopped"
    fi
}

restart(){
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status -p "$PIDFILE" $SERVICENAME
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
